/// Build-time configuration. Override with --dart-define, e.g.
///   flutter build apk --release --dart-define=BASE_URL=https://yourdomain.com --dart-define=STORE=direct
///   flutter build ipa --release --dart-define=BASE_URL=https://yourdomain.com --dart-define=STORE=appstore
class AppConfig {
  /// Your backend. MUST be https — the login cookie is marked Secure.
  static const String baseUrl =
      String.fromEnvironment('BASE_URL', defaultValue: 'https://papertradelab.com');

  /// "direct"   = APK / sideloaded iPhone build from your website → Cashfree checkout inside the app.
  /// "play"     = Play Store build → no purchase screens or links (Play policy);
  ///              users subscribe elsewhere and simply log in.
  /// "appstore" = App Store / TestFlight build → same as "play". Apple (guideline 3.1.1) only
  ///              allows its own In-App Purchase for digital subscriptions, so a Cashfree
  ///              checkout inside an App Store build would be rejected.
  static const String store = String.fromEnvironment('STORE', defaultValue: 'direct');

  static bool get canPurchaseInApp => store == 'direct';

  static const String appName = 'PaperTradeLab';
  static const String supportEmail = 'support@papertradelab.com';
  static const String disclaimer =
      'Signals are generated by an automated paper-trading strategy for education and '
      'analysis. They are not investment advice. Past performance does not guarantee '
      'future results. Trading derivatives involves risk of loss.';
}
